// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmubhgYh48UnYZUOnGbGk2PcxSdBxKX6A',
    appId: '1:1028807949556:web:1f09b0201eae8a1a1cb2a1',
    messagingSenderId: '1028807949556',
    projectId: 'ntapp-b3b5d',
    authDomain: 'ntapp-b3b5d.firebaseapp.com',
    storageBucket: 'ntapp-b3b5d.appspot.com',
    measurementId: 'G-HG61G3LJMC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOPj6Z79AMLApJ9k2YpffXg8-8JaazWik',
    appId: '1:1028807949556:android:1ff68e2d690a7c391cb2a1',
    messagingSenderId: '1028807949556',
    projectId: 'ntapp-b3b5d',
    storageBucket: 'ntapp-b3b5d.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmubhgYh48UnYZUOnGbGk2PcxSdBxKX6A',
    appId: '1:1028807949556:web:58a3f5e51983a0c71cb2a1',
    messagingSenderId: '1028807949556',
    projectId: 'ntapp-b3b5d',
    authDomain: 'ntapp-b3b5d.firebaseapp.com',
    storageBucket: 'ntapp-b3b5d.appspot.com',
    measurementId: 'G-X2254KZ8T4',
  );
}
